### ISSUE TITLE
About test code

### ISSUE THREAD

**Issue by yexianyao** [DAMO-DI-ML/KDD2023-DCdetector#4]
Thank you for your excellent work, but I am confused about the code in this test,
https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/bb2c19f137261f1e32a3429cd91a58abde6c0170/solver.py#L196-L224
 Why multiply temperature? This variable doesn't seem to be mentioned in the paper and is not used during training phase.

**Comment by yyysjz1997** [comment]
> Thank you for your excellent work, but I am confused about the code in this test,
> 
> https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/bb2c19f137261f1e32a3429cd91a58abde6c0170/solver.py#L196-L224
> 
> 
> Why multiply temperature? This variable doesn't seem to be mentioned in the paper and is not used during training phase.

Thanks for your attention to DCdetector and this fine issue. 'Temperature' is a hyperparameter, which is also used in the [Anomaly Transformer](https://github.com/thuml/Anomaly-Transformer/blob/main/solver.py) code. So, we tend to keep it in the Dcdetector in order to ensure a fair comparison. You can also see the description of this parameter in [Anomaly Transformer's repo issue](https://github.com/thuml/Anomaly-Transformer/issues/12).

**Comment by yexianyao** [comment]
Thank you for your answer.

**Comment by yexianyao** [comment]
https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/bb2c19f137261f1e32a3429cd91a58abde6c0170/solver.py#L229C1-L262C1
Hello,

**Comment by yyysjz1997** [comment]
> https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/bb2c19f137261f1e32a3429cd91a58abde6c0170/solver.py#L229C1-L262C1 Hello, The variable "input" is defined at lines 231 and 266 but is not used. Should we add the line "series, prior = self.model(input)" below?

Thanks! Actually, we don't need to add this line.

**Comment by yexianyao** [comment]
Thank you.
